name: Validate Issue Dependency Graph

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
      - name: Regenerate issue graph
        run: |
          python architecture/scripts/generate_issue_graph.py \
            --metadata architecture/issues-metadata.json \
            --report architecture/ARCHITECT_REPORT_FINAL_2025-10-16.md \
            --owner katarinasvedman --repo foundry-demo-agent-framework-WIP
      - name: Fail if graph drift detected
        run: |
          git diff --name-only --exit-code || (echo 'Issue dependency graph out of date. Run generator script.' && exit 1)
